trigger:
- main

pool:
  name: Default  # Name of your self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Adjust to your agent's Node.js version
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: npx playwright test
  displayName: 'Run Playwright tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results/*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
